### ISSUE TITLE
Bug: Website: Search for Product by city/state

### ISSUE THREAD

**Issue by SquidwardHill** [rei/rei-cedar-vue-2#1098]
Hey there, 

I wasn't able to find the appropriate place to add this issue, so feel free to close and move internally to the appropriate team/repo but just wanted to drop an issue that the search tool on the Website doesn't function as expected. (Stumbled upon this as I was attempting to search for something at the Salt Lake City Store Location, reproduced the issue using Chattanooga as a reference) 

Tried in both Brave and Firefox Browsers.

**Steps to reproduce:**
1. Browse to REI website, approve location services in the browser
2. [Search for an item](https://www.rei.com/product/494186/yakima-sks-lock-cores-package-of-4)
3. Click the "Find item in store" link
4. Type in Chattanooga, click Search icon (returns error message)
5. Type in '37415' and click search (returns results, is the same location)

<img width="1624" alt="Screen Shot 2022-05-28 at 5 58 50 AM" src="https://user-images.githubusercontent.com/29778718/170824709-132cc610-d4a3-4ad1-bfe8-c4bc8c03aaab.png">

**Comment by benjag** [comment]
Hi @SquidwardHill, thanks for opening an issue and I very much appreciate the repro steps.

FWIW, that search functionality requires a state when searching by city (i.e. Enter ZIP code or **city, state**) so while "Chattanooga" or "Salt Lake City"  will not work, "Chattanooga, TN" and "Salt Lake City, UT" will. Regardless, I will pass along your feedback to the internal team.

Thanks again!
