### ISSUE TITLE
Cedar Heading not respecting level modifer

### ISSUE THREAD

**Issue by megafatsquirrel** [rei/rei-cedar-vue-2#342]
<cdr-heading level="1">Basic Information</cdr-heading>

Regardless of level used the font-size is set to 16px.

**Comment by mhewson** [comment]
Size values for heading are set via the modifier, with level attribute used for the proper semantic structuring of a page.  This component is subject to change as our design team is actively working on typography.
see: http://rei.github.io/rei-cedar/#cdr-heading, if you expand the code sample you can change the modifier to effect size, type family and other typographical values.
see: https://brand.ai/rei-digital-experience-team/digital-rei-brand for the modifier values excepted.

**Comment by megafatsquirrel** [comment]
Thanks, that makes sense. I miss read the documentation.
