### ISSUE TITLE
Cedar button "link" modifier not working

### ISSUE THREAD

**Issue by megafatsquirrel** [rei/rei-cedar-vue-2#343]
<cdr-button modifier="link">Don't Specify</cdr-button>

Should look like a link, but instead keeps it button styling.

**Comment by mhewson** [comment]
Hi @megafatsquirrel, please verify your component looks as follows?
`<cdr-button modifier="link">Link</cdr-button>`

**Comment by lancetharper** [comment]
This depends on having the css for cdr-a too. If you don't have that included, that modifier won't work.

We'll have to note that in the docs for it.

**Comment by lancetharper** [comment]
Including the cdrA css fixed this.

I'll add a note in the button readme and will do the same for anchor with the "button" modifier

**Comment by mhewson** [comment]
@lancetharper, should we add a per-dependancy into these components to grab the needed css files?

**Comment by megafatsquirrel** [comment]
Sorry I missed the notifications. Lance set me right with including the cdrA css.
