### ISSUE TITLE
Components have single, non-intuitive named export rather than default export

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#354]
Current:
```
import { CdrButton } from '@rei-co-op/cedar-button';
```

Expected:
```
// very much preferred
import Button from '@rei-co-op/cedar-button';

// does not make as much sense intuitively, but still better:
import { CedarButton } from '@rei-co-op/cedar-button';
```

**Comment by lancetharper** [comment]
Default export is a plugin, this is intentional.

```
import Vue from 'vue';
import Button from '@rei-co-op/cedar-button';

Vue.use(Button); // now it's available globally
```

The other export is only offered in case somebody NEEDS to do it that way.

**Comment by jnields** [comment]
Hm... OK, sure. Though I would say it may be easier to just export it as a component and allow clients to use it globally if they would really like to.

This is pretty simple for us to do:
```
// main.js
import CdrButton from '@rei-co-op/cedar-button';
import CdrA from '@rei-co-op/cedar-a';
import App from './app';

Vue.mixin({
  components: {
    CdrButton,
    CdrA
  },
});

new App().$mount('#root')
```

**Comment by jnields** [comment]
otherwise I think it makes sense to either change the components’ names or the package names so that they match, you know?

**Comment by jnields** [comment]
Global variables are an anti-patttern and discourage code-reuse. Will you please discourage use of `Vue.use` as this will cause problems for code-sharing not too far down the road


Scenario:
I create a component, `@rei/foo`,  to use `@rei/cdr-btn@1.0.0`:

```
import CdrBtn from '@rei/cdr-btn';
Vue.use(CdrBtn);
export default {
  name: 'foo',
  render() { return <cdr-button /> }
}
```

then that is used on a page that also uses `@rei/cdr-btn`, but a different version: `@rei/cdr-btn@2.0.0`

so when I do

```
import CdrBtn from '@rei/cdr-btn';
Vue.use(CdrBtn);
```

the page is now incompatible with my package `@rei/foo`

There's no technical restriction to needing to use a plugin instead of referencing the component directly.

```
import CdrBtn from '@rei/cdr-btn';

export default {
  components: { CdrBtn },
  render(h) {
    return <cdr-btn />
  }
};
```

or 

```
import CdrBtn from '@rei/cdr-btn';

export default {
  render(h) {
    return <CdrBtn />
  }
};
```

And even still, you can still reference the component globally if for whatever reason you want your code to face issues with reusability in the name of not having to import the button by using a global mixin

```
Vue.mixin({ components: { CdrBtn } })
```

So why encourage use of a global plugin?

**Comment by lancetharper** [comment]
This is on our radar -- hopefully getting around to doing this soonish. 

We'll probably output two files -- component and plugin. the component would be the main but we still want to keep plugins too because they allow for use cases where there might not be a build system.

**Comment by jnields** [comment]
@lancetharper awesome

Have you considered outputting a UMD build ilo of a plugin?

**Comment by jnields** [comment]
@lancetharper awesome -

Have you also considered just outputting a UMD build? Then it's compatible w/ whatever - regardless of whatever is (or isn't) being used to bundle

**Comment by lancetharper** [comment]
The current output is UMD
