### ISSUE TITLE
components should include a "style" field in the `package.json`

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#374]
Postcss uses the [style field](https://github.com/postcss/postcss-import) to indicate where styles are included. This is basically the closest thing to a standard for including style alongside javascript that seems to exist for npm modules and would be helpful to include

**Comment by lancetharper** [comment]
This was done as part of the npm package org/name changes

https://github.com/rei/rei-cedar/blob/cedar2/src/components/anchor/package.json
https://www.npmjs.com/org/rei
