### ISSUE TITLE
peerDependencies are being bundled into component dist files

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#384]
Right now, you're using webpack for your build
Also right now, cdr-media-object is ~20kb minified despite the source code being 3.7kb unminified

Ideally, when I import a dependent module, that module descriptor's `main` is keeping track of its dependencies via require statements

Here's where webpack / browserify are somewhat unsuited toward transpiling library code - their motivations are for "rolling up" or "bundling" all the assets together into a file for final distribution of assets to clients - not for transpiling library code. Sure, they may be configured to serve your purpose, but for me at least this has led to issues with sourcemaps and the configuration is easy to get wrong

The easiest way to do this in my experience is to just use babel-cli directly - e.g.

```
#!/bin/bash
# transpile all code in src from ES6 to ES5 with commonjs requires
BABEL_ENV=commonjs babel src -d dist
# transpile all code in src from ES6 to ES5 with ES module dependency management
BABEL_ENV=es babel src -d es
```

This was a big motivation for us opting into using jsx in lieu of vue template syntax, because I don't believe that babel has a robust plugin / preset to transform vue templates to ES5 code.

But ultimately, we just need that ES5 code.

So to fix this for us, you could figure out how to get webpack to build correctly for a commonjs target without including its peerDependencies (configure [externals](https://webpack.js.org/configuration/externals/)), compile your templates manually and programmatically, or use babel w/ babel-plugin-vue-jsx & jsx

Another issue - this can be very important - webpack doesn't have the ability to output an 'ecmascript module' build. This is necessary for tree-shaking. Adding a 'module' field to your package.json is the current way to achieve this at least in webpack and rollup without extra configuration.

More details on what this means here: https://github.com/rollup/rollup/wiki/pkg.module
And for even more info, node has support for 'mjs' files (ecmascript module files) on their roadmap.
https://nodejs.org/api/esm.html

**Comment by jnields** [comment]
Oh, also, thank you for using `babel-plugin-transform-runtime`!

The babel helper requires, e.g. 
```
import _defineProperty from 'babel-runtime/helpers/defineProperty';
import _extends from 'babel-runtime/helpers/extends';
```
right now would also be bundled rather than being referenced as `require`s for the same reason

**Comment by KrisKnabel** [comment]
I believe the desire for this is influenced by JSX usage which I have heard is no longer part of REI's supported libraries/frameworks.  This is slightly related to the other issue #353 as it may be our desire to provide our packages in a format of `source/library code' instead of compiled/minified end use code.  We should discuss as a team.

**Comment by mhewson** [comment]
This is no longer relevant

**Comment by jnields** [comment]
This is unrelated to jsx - if you are using webpack you need to configure [externals](https://webpack.js.org/configuration/externals/) correctly ... Dunno if this has been done or not since I filed this bug

**Comment by cowills** [comment]
@jnields it appears that this was actually done despite this issue being rejected ¯\_(ツ)_/¯ https://github.com/rei/rei-cedar/commit/e0d9763
