### ISSUE TITLE
cdr-icon lists svgxuse as a peer dependency

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#409]
It should not - svgxuse will break vue ssr hydration and generally cause problems because it mutates elements that should be under vue's control

**Comment by lancetharper** [comment]
This has already been removed for the upcoming 0.2.0 release.

A polyfill of some kind (whether svgxuse or something else) will be needed to support sprite usage though.

**Comment by jnields** [comment]
you don't need a polyfill if the defs are on the page - ie `<use href="#foo">`- just can't be an external reasource for IE11
