### ISSUE TITLE
Cedar Components don't work as intended w/ rollup / webpack 4

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#420]
To use a component, I have to do this:

```
import CdrImg from '@rei/cdr-img';

const Component = CdrImg.CdrImg;
```

this is because you're not actually outputting a named export - that would require a module build.

Instead the main files are `module.exports = { CdrImg: [actual component] };`

Also if you did `export default ` instead of `export { defaut as foo }` this wouldn't be an issue and you wouldn't need to disable the linter warning 🙃

**Comment by KrisKnabel** [comment]
Will review in our next dev meeting.

**Comment by KrisKnabel** [comment]
Using object destructuring would solve your issue:
``` import { CdrImg } from `@rei/cdr-img' ```

This is shown in our documentation here: https://rei.github.io/rei-cedar-docs/components/image/?active-tab=api
