### ISSUE TITLE
Remove svgxuse from peerdepencies of icon

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#422]
svgxuse doesn't work with Vue - it corrupts the DOM (because the svgs are supposed to be under the control of Vue) and causes errors in IE

**Comment by jnields** [comment]
related: you can still use xlink:href and use if you put the icons in a definition at the top of the markup and have xlink:href point to an id on the page (e.g. `xlink:href="#some-id"`)

**Comment by lancetharper** [comment]
For visibility:

`svgxuse` was removed in cdr-icon 0.2.0

this is related to mediaObject (which has a dependency on icon 0.1.0) and will be fixed once media object is updated again
