### ISSUE TITLE
cdr-grid missing `style` entry in package.json

### ISSUE THREAD

**Issue by coleww** [rei/rei-cedar-vue-2#500]
the cdr-grid component is missing a `style` entry in the package.json (https://github.com/rei/rei-cedar/blob/next/src/components/grid/package.json) which causes postcss imports to not work (i.e, `@import url('@rei/cdr-grid');`) This issue can be worked around, but other cedar components appear to have a style entry.

**Comment by mhewson** [comment]
@lancetharper can you review and make a recommendation to remediate?

**Comment by lancetharper** [comment]
Yes, I'll add this in with the next release 👍

**Comment by lancetharper** [comment]
@coleww added in version `1.0.2`
