### ISSUE TITLE
Cdr-button uses non-standard require statement - breaking build

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#501]
dist/cdr-button.js contains the following

`require("@rei/cdr-icon/dist/cdr-icon.css")`

this is an invalid require statement and it should be removed

**Comment by zfolwick** [comment]
what version of button are you using?

**Comment by darintrimillos** [comment]
This is fixed in version `1.0.3-alpha.0`.

**Comment by darintrimillos** [comment]
Version 1.0.3 has been released, which fixes this issue. Thanks for catching.
