### ISSUE TITLE
Upgrading cdr-card to use cdr-assets: 0.3.0

### ISSUE THREAD

**Issue by goldendoodledev** [rei/rei-cedar-vue-2#508]
Hi everyone! I'm trying to update the cedar components in my project, but here is the problem I'm having:

All the upgraded cedar components I'm using are dependent on `cdr-assets: 0.3.0`, except for `cdr-card`.

The latest version of `cdr-card` that I can install is `0.2.0`, which looks like it's dependent on  `cdr-assets: 0.1.0`.

Could I please request for cdr-card to be upgraded to `cdr-assets: 0.3.0`? Thank you!

**Comment by mhewson** [comment]
@efine package has been bumped to 0.2.2 -- https://codesandbox.io/s/n9wppzo354
