### ISSUE TITLE
REI.com star-fill issue on live site

### ISSUE THREAD

**Issue by robatron** [rei/rei-cedar-vue-2#531]
Hi folks, I'm not sure if this is related to `rei-cedar`, but I noticed y'all's _filled_ rating star colors are grey, so they appear like _unfilled_ stars:

![screen shot 2018-11-20 at 3 54 05 pm](https://user-images.githubusercontent.com/127095/48810221-f4dec300-ecdc-11e8-9028-42aa466f10ff.png)

Examples:
- (screenshot product) https://www.rei.com/product/139918/stickers-northwest-go-outside-sticker
- https://www.rei.com/product/139963/stickers-northwest-pacific-northwest-glass-triangle-sticker

CC @mhewson @panganibanpj

**Comment by mhewson** [comment]
@robatron great to see you on here :) I will look into this - got a device and browser to check against? I'm not reproducing this locally

**Comment by mhewson** [comment]
I am unable to reproduce this issue and am closing for now

**Comment by robatron** [comment]
Hey @mhewson , sorry for the delay. I can repro the error on Chrome v72.0.3622.0 (Official Build) dev (64-bit) on Mac OS X 10.13.6, but it seems to be working fine on Firefox v63.0.3 (64-bit) and Safari v12.0.1 (13606.2.104.1.2)

Screenshots of, left to right, Firefox, Safari, and Chrome:

<img width="1680" alt="screen shot 2018-11-27 at 11 48 56 am" src="https://user-images.githubusercontent.com/127095/49107686-433f1500-f23b-11e8-9f33-f77e280951fe.png">

**Comment by mhewson** [comment]
@rhuded, see above for matrix -- Assigned to product team for investigation
