### ISSUE TITLE
Cdr-link onClick feature

### ISSUE THREAD

**Issue by eekberg-rei** [rei/rei-cedar-vue-2#558]
**Feature request:**
Add `onClick` prop to CdrLink.

Similar to button components, link tags may be used to trigger functions on click instead of redirecting users. 

[ ] Add `onClick` prop to script
[ ] Add `@click="onClick"` to template
[ ] Remove default value `#` from `href` prop

**Comment by mhewson** [comment]
That would make this not a link - we define a link to be a navigable element only for accessibility purposes. If you are looking for onClick support you are able to use the cdr-button component. I'm opening a ticket to support link styles within the button component via  modifier="link" or  modifier="link--standalone"

**Comment by eekberg-rei** [comment]
Link-like styles on a button sounds perfect. Thanks for the quick response.

**Comment by darintrimillos** [comment]
Actually, ended up adding the onClick prop to CdrLink as originally requested to keep the style crossover at a minimum. I didn't remove the `#` from `href` and it seemed to work fine. Let me know if you still need that removed. https://www.npmjs.com/package/@rei/cdr-link/v/1.1.0-alpha.0

**Comment by eekberg-rei** [comment]
The `onClick` prop for `cdr-link` does not appear to be working, but it does work for `cdr-button`.

My current workaround is
```jsx
<cdr-button class='cdr-link_1.1.0-alpha.0 cdr-link--standalone_1.1.0-alpha.0' onClick={this.myMethod}>clickable text</cdr-button>
```

**Comment by eekberg-rei** [comment]
Looking into it further, `onClick` does not seem to work on either the `cdr-link` or `cdr-button` components. Perhaps that is because my team is using `JSX` instead of Vue templates.

**Comment by mhewson** [comment]
@zfolwick can you verify the onClick functionality to button and link?

@eekberg-rei the cedar project does not support JSX with our architecture, so while I hope to be able to help you if it is a JSX issue you may need to solve for this on your end or factor out the JSX to support the Vue vanilla expectations.

**Comment by darintrimillos** [comment]
@mhewson I'll sync up with @zfolwick about testing the onClick functionality for link. We'll want to keep that.

**Comment by bschwartz757** [comment]
Looking at the code for this component, it does not seem to accept on `onClick` prop. For a link-as-button (my current use case), this renders the component not useful - I have a component that needs to render as a link, but act as a button.

Additionally, the link styling works on mobile layout but does not work on desktop layout (the link becomes a full-width button with more or less browser default button styling at `sm` and above.)
