### ISSUE TITLE
Add breakpoint notation in Docs

### ISSUE THREAD

**Issue by eekberg-rei** [rei/rei-cedar-vue-2#559]
**Feature:**
Add a "Breakpoints" tab to your site docs explaining the breakpoints widths and their notation (e.g. "@md", "@xs"). 

Example: 
* https://vuetifyjs.com/en/framework/breakpoints

**Comment by mhewson** [comment]
Thank you for the request, I would like to help get this on our roadmap - please request this enhancement via our feature request form https://airtable.com/shrcbq9CHthuMO7AC

**Comment by mhewson** [comment]
thanks for using the request form I will work with the team to prioritize
