### ISSUE TITLE
cdr-checkbox not reflecting bound value

### ISSUE THREAD

**Issue by zcrumbo** [rei/rei-cedar-vue-2#564]
I'm binding the value of the checkbox to the results of an expression - a situation can occur where clicking on the box updates the internal `newValue` state to `true` but the prop `value` remains `false`, and the checkbox remains in the checked state

expected behavior:
If value of component is bound by parent, checkbox state will always reflect that value

Actual behavior: 
checkbox state reflects value of internal state `newValue` even if it conflicts with bound value prop.

```jsx
...
function handleClick(e) {
 console.log(e)
}

render() {
 return(
  <CdrCheckbox value={() => false} onClick={handleClick}>
 )
// on click, console will log true, but Component prop is still false. Inspecting component will reveal internal state of newValue is true, but value prop is still false
}
...

```

**Comment by lancetharper** [comment]
cdr-checkbox is meant to be used with `v-model`. 

If you are using jsx/render functions you have to handle that logic yourself. https://vuejs.org/v2/guide/render-function.html#v-model

Edit:
Looks like vue has a babel preset that supports `vModel` in jsx too -- https://github.com/vuejs/jsx
