### ISSUE TITLE
Theming functionality

### ISSUE THREAD

**Issue by luludan** [rei/rei-cedar-vue-2#599]
I've just started on a new project that is using cedar in a vue project.

Just wanted to know if there is any level of theming available (mainly just to change colors) without just creating overwriting classes to change colors.

I can see that the build distributed via npm has compiled css for components, so while I can re-use your existing scss variables I cannot modify and have them reflect in the components themselves

What would you recommend for at least applying our own branding colors to buttons etc rather then the default colors?

**Comment by mhewson** [comment]
Hi @luludan thanks for the request!
unfortunately we don't support theming at this time - though it may pop into our roadmap  to support a component toggle for such functionality in the future. If you are using the project from this repo you should be able to reset the color values directly within the component css.
