### ISSUE TITLE
Paginator documentation gives problematic recommendations for link clicks

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#604]
Vue-router specifically does this for link clicks:

https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L105

This isn't in the docs and I worry will cause issues for people who just call `event.preventDefault()` without thinking about it.

Perhaps you can use a `<RouterLink/>` component instead? Or perhaps you can let users render the page via a scoped slot?  (provide link content, which could be a slot, and the user provides the link component)

**Comment by cowills** [comment]
Is the issue that the docs use `e.preventDefault()` but that affects how vue-router works?  https://rei.github.io/rei-cedar-docs/components/pagination/?active-tab=api#usage-with-vue-router 
Or are you requesting a change to the pagination component to allow passing a custom component to use instead of the default `a` tags?

**Comment by jnields** [comment]
Issue:

If you have your click handler just call `e.preventDefault()` without checking for meta keys, `target="_blank"`, etc., you break default browser behavior. Vue-Router, React-Router, etc. all handle this within their link components.

As a potential solution, your API might look something like this:

```
<Paginator
  {/* default to this is a function that returns a wrapper on `<a>` with same API as RouterLink, perhaps? */}
  getLinkComponent={() => RouterLink}
  totalPages={10}
  currentPage={3}
/>
```

**Comment by jnields** [comment]
Another solution might look like this:

```
<Paginator
  {...{
    props: {
      totalPages: 13,
      currentPage: parseInt(queryString.parse(history.location.search).page, 10) || 1,
      navigate(n) {
        // for select change
        this.$router.push(`?page=${n}`); 
      },
    },
    scopedSlots: {
      link: ({ n, className, content }) => (
        <RouterLink class={className} to={`?page=${n}`}>{content}</RouterLink>
      ),
    },
  }}
/>
```

**Comment by cowills** [comment]
in cedar 3.0.0 pagination now supports scoped slots for rendering custom links: https://rei.github.io/rei-cedar-docs/components/pagination/#link-scoped-slots
