### ISSUE TITLE
Disabled cdr-button has very low contrast (accessibility related)

### ISSUE THREAD

**Issue by goldendoodledev** [rei/rei-cedar-vue-2#607]
I noticed that cdr-buttons are very low contrast between the background color and text color when disabled.  They might need a new design solution to make them more accessible.

**Comment by cowills** [comment]
<img width="750" alt="Screen Shot 2019-05-02 at 2 29 43 PM" src="https://user-images.githubusercontent.com/48567940/57108160-c8e15800-6ce6-11e9-9cbc-a3761b3be427.png">

**Comment by lancetharper** [comment]
Disabled elements are not required to meet contrast minimums: https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#inactive-controls

**Comment by lancetharper** [comment]
@elizabethfinedev I raised this up with our designers and they recognize that WCAG are minimum requirements and are looking into maybe updating the colors to try and bump contrast up a bit.
