### ISSUE TITLE
Breadcrumbs cause FOUC-like experience with SSR

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#608]
The logic for breadcrumb truncation runs on mounted, meaning that before the page javascript loads, the breadcrumbs will render without truncation on a server-rendered page

**Comment by KrisKnabel** [comment]
This is due to needing to get the rendered width prior to the breadcrumb being displayed to the user so that it does not jitter/shift at page load.  We should find an alternative approach.  Thank you for filing this!  I will follow up with the team and we will discuss next steps.

**Comment by jnields** [comment]
Another thing to consider: for SEO we very probably want the links to still be on the page (so hidden instead of not rendered)

**Comment by KrisKnabel** [comment]
Jira task created and added to Cedar Backlog.
https://issues.rei.com/browse/CDR-718

**Comment by cowills** [comment]
as of cedar 3.0.0, breadcrumb no longer runs this truncation logic on page load, which avoids the FOUC when using SSR.
