### ISSUE TITLE
Breadcrumbs do not allow for event handlers to be attached to links (`items` prop)

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#609]
We could potentially need `onEnter`, `onFocus`, `onClick`, etc.

**Comment by jnields** [comment]
Suggestion - maybe something like this?

```
<template>
  <ul class="breadcrumbs">
    <li v-for="item in items">
      <a v-bind="item.link">{{item.label}}</a>
    </li>
  </ul>
</template>
```

**Comment by KrisKnabel** [comment]
Jira task created and added to our backlog.
https://issues.rei.com/browse/CDR-719

**Comment by cowills** [comment]
Breadcrumb has been updated in cedar 3.0.0 to support a `link` scopedSlot: https://rei.github.io/rei-cedar-docs/components/breadcrumb/?active-tab=overview#link-scoped-slot
