### ISSUE TITLE
Accordions are not stateless

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#610]
Accordions maintain internal state to handle toggling open / closed state which makes it impossible to satisfy a requirement such as "when opening an accordion close all others"

**Comment by jnields** [comment]
proposed change:

```
<Accordion opened={false} toggle={toggle}>
</Accordion>
```

**Comment by darintrimillos** [comment]
Thanks for the feedback, we'll look into this and get back to you.

**Comment by darintrimillos** [comment]
This has been fixed in the 3.0.0 release of Cedar.
