### ISSUE TITLE
Icon documentation doesn't show available icons

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#619]
Can we get something like this?

https://useiconic.com/open/

Where the icons preview and we can see their name? Otherwise it's kind of hard to know what's available

**Comment by cowills** [comment]
https://rei.github.io/rei-cedar-docs/components/icon/?active-tab=design-guidelines#icon-library does this cover what yr looking for? @jnields

**Comment by lancetharper** [comment]
We should put a link to that in the API tab probably 👍

**Comment by lancetharper** [comment]
Will go live with next docs site update https://github.com/rei/rei-cedar-docs/pull/345#pullrequestreview-244052979
