### ISSUE TITLE
Cedar Input doesnt update when you change the v-model attr

### ISSUE THREAD

**Issue by goldendoodledev** [rei/rei-cedar-vue-2#620]
Hi there,

I'm working on a form within a modal.  The form looks like this:
`<cdr-input v-model="emailValue" />`

I'd like to reset the cdr-input value when the modal closes. I tried to do:
`onModalClose () {
    this.emailValue = '';
},`

However, it seems like updating the v-model doesn't update the actual value of the input field. Is this a bug or intended?

Thank you!

**Comment by KrisKnabel** [comment]
Thank you for your feedback Elizabeth.  I will take a look at this.  Could you clarify a couple things for me?  Is the modal destroyed on close or just hidden?  Are you redisplaying the modal with the input after it's closed?  How are you detecting that input value is not updating?

**Comment by cowills** [comment]
it looks like this is a bug in cdr-input 1.0.1 and 1.0.2, introduced by this commit: https://github.com/rei/rei-cedar/commit/45d6070

downgrading to 1.0.0 seems to work, though that may introduce other errors if yr depending on something that was added in 1.0.1 or 1.0.2 https://github.com/rei/rei-cedar/blob/master/src/components/input/CHANGELOG.md 
 
https://codesandbox.io/s/cdrinput-x1v5g (components/default.vue contains the example)

**Comment by KrisKnabel** [comment]
Disregard my questions Elizabeth.  Try Cole's recommendation of using version 1.0.0.  If that doesn't work, I can get you a hotfix in an alpha or beta if this is a blocker.  Let me know.

**Comment by KrisKnabel** [comment]
We have accepted this defect and are planning to have this fix published soon in our Summer Cedar Release.

**Comment by KrisKnabel** [comment]
This has been fixed in the latest (Summer) Cedar release.
