### ISSUE TITLE
<CdrInput /> not firing change event

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#623]
related: #620

**Comment by KrisKnabel** [comment]
Yes definitely a bug.  May try to get this piggy backed on the v-model update.  Thank you Joe!

**Comment by lancetharper** [comment]
Input doesn't fire a change event, this is correct. The docs for it are wrong and missing all of the actual events emitted by input -- we'll get that updated.

They should be `input`, `blur`, `focus`, `paste`, and `keydown`.

**Comment by lancetharper** [comment]
Docs for this have been updated and are now correct. https://rei.github.io/rei-cedar-docs/components/input/?active-tab=api&active-link=events
