### ISSUE TITLE
<CdrInput /> box-shadow not visible on iOS safari

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#627]
Can this be a border instead of a box-shadow?

**Comment by cowills** [comment]
the box-shadow is used in addition to the border and is needed to indicate an active/focused state, so we can't just use border here. though it looks like the border isn't showing up on IOS safari either 😬

<img width="538" alt="Screen Shot 2019-06-18 at 11 55 16 AM" src="https://user-images.githubusercontent.com/48567940/59711433-f95e5200-91bf-11e9-97f7-8b9514b5f186.png">

**Comment by cowills** [comment]
https://stackoverflow.com/a/8199147 looks like this fixes the problem

**Comment by KrisKnabel** [comment]
This has been fixed in the latest (Summer) Cedar release.
