### ISSUE TITLE
cdr-tabs Content container height

### ISSUE THREAD

**Issue by matthewkoehl** [rei/rei-cedar-vue-2#636]
Per discussion with Marie and Jay, Jay requested that this be submitted - as he believes the content container's auto height should adjust to show all containing content by default, unless height is otherwise specified.

**Comment by KrisKnabel** [comment]
I am investigating this now.  Thank you @matthewkoehl

**Comment by KrisKnabel** [comment]
Spoke with Cedar team and we will be updating the tabs component with height logic.  There are multiple behaviors/solutions we need to investigate in order to provide the best solution.  This will likely be pushed into the Cedar Fall release.

**Comment by cowills** [comment]
This will be fixed in the summer release of cedar (v6.x.x). Passing `height="auto"` now enables the tabs height to adjust to content size dynamically
