### ISSUE TITLE
cdr-tabs Overflow container - Scroll bar does not show in MacOS Browsers

### ISSUE THREAD

**Issue by matthewkoehl** [rei/rei-cedar-vue-2#637]
Scroll bar does not show when overflow content is present in browsers on MacOS, but they do show up on Windows systems browsers. 

Without the scroll bar, there is no indication to the user that there is additional content contained within the overflow container.

**Comment by KrisKnabel** [comment]
Looking into this now.  Thank you for creating this @matthewkoehl  I will update this issue soon with more details about my findings.

**Comment by KrisKnabel** [comment]
After meeting with the team on this, scroll bars not showing on overflow is standard within Apple's Design Standard.  We will be updating the tab panel with extra height logic that will prevent overflow (https://github.com/rei/rei-cedar/issues/636).  We will also be investigating alternative recommendations/guidelines for UX design as it pertains to overflow.  I am currently investigating a workaround that will allow users extra clarity that the content is scrollable and will post update here.
