### ISSUE TITLE
cdr-cta cannot be set to full-width only at a breakpoint

### ISSUE THREAD

**Issue by darintrimillos** [rei/rei-cedar-vue-2#643]
CTA needs some more granular options so that it can be full-width only at the XS breakpoint.

**Comment by cowills** [comment]
looks like none of the CTA options allow for passing breakpoints 🤔

**Comment by jakerohr** [comment]
It may be a separate issue, but sizing options similar to what cdr-button has would be awesome as well.

**Comment by cowills** [comment]
@jakerohr as I understand it, the lack of size options for CTA was an intentional design decision. the idea is that the CTA should expand to be the size of the text contained within it.

**Comment by darintrimillos** [comment]
CTA can now be set `fullWidth` at a specific breakpoint in Cedar 3.0.0.
