### ISSUE TITLE
Webpack is deleting imported CSS in production builds

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#770]
This is present on versions 3 and 4

Because cedar has marked the package as `"sideEffects": false`, webpack sees CSS files, too, as being side-effect free and drops them.

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> Note that any imported file is subject to tree shaking. This means if you use something like css-loader in your project and import a CSS file, it needs to be added to the side effect list so it will not be unintentionally dropped in production mode:

To fix this issue, configure your package to indicate that CSS files emit side effects, e.g. `"sideEffects": ["*.css"]`

**Comment by cowills** [comment]
added to our intake log

**Comment by cowills** [comment]
resolved in 3.0.5 and 4.0.2
