### ISSUE TITLE
Cedar 4.0.2 - <cdr-tabs/> - centered modifier cuts off left `<cdr-tab-panel/>`s in lower resolutions.

### ISSUE THREAD

**Issue by HeavyMedl** [rei/rei-cedar-vue-2#779]
Unable to scroll to the left to reveal first `<cdr-tab-panel/>` in lower resolutions when using `modifier="centered"`.

Steps to repro:
1. Set up `<cdr-tabs/>`

```
<cdr-tabs
    height="500px"
    modifier="centered"

    <cdr-tab-panel
          name="Sustainable travel"
          ....
     </cdr-tab-panel>

    <cdr-tab-panel
          name="Stewards of public lands"
          ....
     </cdr-tab-panel>

    <cdr-tab-panel
          name="Volunteer"
          ....
     </cdr-tab-panel>
</cdr-tabs>
```
2. Lower resolution to enough to invoke hidden overflow for `<cdr-tab-panel/>`s.
3. Scroll panels to the right, then attempt to scroll back to the first panel.

Screenshot

![Screen Shot 2020-02-18 at 11 51 07 AM](https://user-images.githubusercontent.com/4061053/74772626-37c37980-5245-11ea-8587-d042e4bd8264.png)

**Comment by darintrimillos** [comment]
Added to our intake backlog.

**Comment by cowills** [comment]
This was fixed in the Spring release of Cedar (v5.x.x)
